# Generated by Django 2.2.14 on 2021-07-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
