# Generated by Django 2.2.14 on 2021-07-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0002_auto_20210731_0528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
