# Generated by Django 2.2.14 on 2021-08-02 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0006_auto_20210801_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_add']},
        ),
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
