# Generated by Django 2.2.14 on 2021-08-02 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sukeachin', '0008_auto_20210802_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
