# Generated by Django 2.2.14 on 2021-08-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0014_auto_20210804_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
