# Generated by Django 2.2.14 on 2021-08-04 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sukeachin', '0016_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Mobile_no', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Product_name', models.CharField(max_length=150)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Total_price', models.FloatField()),
                ('Shipping_cost', models.FloatField(null=True)),
                ('Grand_total', models.FloatField()),
                ('Orderd_date', models.DateTimeField(auto_now_add=True)),
                ('Payment_method', models.CharField(choices=[('paypal', 'paypal'), ('payoneer', 'payoneer'), ('direct_bank_transfer', 'direct_bank_transfer'), ('cash_on_delivery', 'cash_on_delivery')], default='Cash on Delivery', max_length=50)),
                ('Orderd_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
