# Generated by Django 2.2.14 on 2021-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0018_auto_20210804_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Sub_total',
            field=models.FloatField(null=True),
        ),
    ]
