# Generated by Django 2.2.14 on 2021-08-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0019_order_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_price',
            field=models.CharField(max_length=150),
        ),
    ]
