# Generated by Django 2.2.14 on 2021-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0020_auto_20210805_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_price',
            field=models.FloatField(),
        ),
    ]
