# Generated by Django 2.2.14 on 2021-08-05 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0022_auto_20210805_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Grand_total',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='Sub_total',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
