# Generated by Django 2.2.14 on 2021-08-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sukeachin', '0024_auto_20210805_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('paypal', 'paypal')], default='Cash on Delivery', max_length=50),
        ),
    ]
